# Generated by Django 5.0.6 on 2024-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
