# Generated by Django 5.0.6 on 2024-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverweb', '0002_video_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='video/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='video/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/'),
        ),
    ]
